### ISSUE TITLE
Cache-Control on OPTIONS preflight requests

### ISSUE THREAD

**Issue by betaglop** [betaglop/liOnlineChoicesPlugin#8]
commit 9ee9f8b expected to reduce the number of requests for CORS informations, materialized by OPTIONS requests... sadly it seems not to be taken into account, even if the header is well sent.

@PapsOu ?

**Comment by PapsOu** [comment]
We will need to see with the sysadmin how to manage that with a proxy. 

I've found a solution to bypass Preflight request https://stackoverflow.com/a/31555285

It's a little bit dirty but we should try that.

**Comment by betaglop** [comment]
It's much than dirty...
And AFAIK correct Cache-Control directives should be followed by browsers in the same way than proxy servers, shouldn't it ?

**Comment by GlennCavarle** [comment]
Preflight caching possibilities seems to be limited in CORS Specs and browsers for security reasons:
https://stackoverflow.com/questions/23543719/cors-access-control-max-age-is-ignored

**Comment by betaglop** [comment]
fait
